server:
  port: 7070

spring:
  application:
    name: "OAuth2-Client"
  security:
    oauth2:
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:7070/authorized"
            scope:
              - openid
              - profile
              - READ
              - WRITE
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9090"